# Book settings
title: Time Series Scaling
author: Wen-Ting Wang
logo: ""

# MyST settings
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath

# Interactivity settings
interactivity:
  thebelab: true

# Sphinx settings
sphinx:
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      launch_buttons:
        thebelab: true
      path_to_docs: "docs"
      repository_url: "https://github.com/<your-repo>"
      repository_branch: "main"
      use_fullscreen_button: false
    html_js_files:
      - "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"
    suppress_warnings: ["mystnb.unknown_mime_type"]

# Execution settings
execute:
  execute_notebooks: "off"

# General settings
hide_input: true
highlight_code_blocks: true
